# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "mpt3sas" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime" "space_cache=v2" "discard=async"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@srv" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@snapshots" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/var/lib" = {
    device = "/dev/disk/by-label/var";
    fsType = "btrfs";
    options = ["subvol=@db" "x-initrd.mount" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/var";
    fsType = "btrfs";
    options = ["x-initrd.mount" "subvol=@log" "compress=zstd" "noatime"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXOS-BOOT";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/array" = {
    device = "/dev/disk/by-label/array";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime" "commit=300"];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-label/array";
    fsType = "btrfs";
    options = ["subvol=@data" "compress=zstd" "noatime" "commit=300"];
  };

  fileSystems."/scratch" = {
    device = "/dev/disk/by-label/scratch";
    fsType = "btrfs";
    options = ["compress=zstd" "noatime"];
  };

  fileSystems."/mnt/btrfs-root" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = ["subvolid=5" "noatime"];
  };

  fileSystems."/mnt/btrfs-var" = {
    device = "/dev/disk/by-label/var";
    fsType = "btrfs";
    options = ["subvolid=5" "noatime"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-06fc8d9a4c8f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-830a559cb0f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-b9b2d347c34a.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.incusbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tap4c126fbc.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth3d2d407.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth5ddb264.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe195562.useDHCP = lib.mkDefault true;
  # networking.interfaces.vmbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
